version: 2

models:
  - name: transformed_data  # This is the model created from the SQL file
    description: "This model transforms the cleaned_data for analysis."
    columns:
      - name: Channel Title
        description: "The title of the channel."
      - name: Channel Username
        description: "The standardized username of the channel."
      - name: Message ID
        description: "The cleaned message ID."
      - name: Message Text
        description: "The content of the message."
      - name: Date
        description: "The date the message was sent."
      - name: Media Path
        description: "The path to any media associated with the message."
